MERGE INTO {dataset_refined}.{destination_table} AS T
USING (
            SELECT 
                    u.id AS user_id,
                    u.team_id, 
                    u.usertype_id, 
                    u.userstatus_id, 
                    u.useravatar_id, 
                    u.template_id, 
                    u.agentid, 
                    u.externalid, 
                    u.username, 
                    u.name, 
                    u.lastname, 
                    u.email, 
                    u.place, 
                    u.cell, 
                    u.position, 
                    u.phone, 
                    u.branch, 
                    u.cellphone, 
                    u.description, 
                    u.password, 
                    u.img, 
                    u.newsletter, 
                    u.level, 
                    CAST(u.touruser AS TIMESTAMP) AS touruser, 
                    CAST(u.touradm AS TIMESTAMP) AS touradm, 
                    u.entrytime, 
                    u.exittime, 
                    u.acceptprivacy, 
                    u.blockdm, 
                    u.blockmobile, 
                    u.blockscale, 
                    u.changepassword, 
                    u.status, 
                    u.uac_id, 
                    u.cpf, 
                    u.leader, 
                    u.changeusername, 
                    u.mention, 
                    u.nid, 
                    CAST(u.created AS TIMESTAMP) AS created, 
                    u.created_by, 
                    CAST(u.firstaccess AS TIMESTAMP) AS firstaccess, 
                    CAST(u.lastaccess AS TIMESTAMP) AS lastaccess, 
                    u.idiom_id, 
                    id.code as idiom_code, 
                    u.fuso_name, 
                    u.login, 
                    CAST(u.acceptprivacy_datetime AS TIMESTAMP) AS acceptprivacy_datetime, 
                    u.acceptprivacy_from, 
                    u.acceptprivacystore, 
                    hy.leaderid as hierarchy_leaderid, 
                    tm.subdomain, 
                    (SELECT max(mh.created_at) FROM {dataset_trusted}.mood_history mh where u.id = mh.user_id and u.team_id = mh.team_id and u.database = mh.database) as mood_lastchange, 
					 --CASE
                       --   WHEN ur.user_restrict IS NOT NULL THEN 1
                         -- ELSE 0
                    0 restricted_user,    --END restricted_user,
					
                    u.database, 
                    CAST(u.dateload AS TIMESTAMP) AS dateload,
					u.op,
					CAST(CONCAT(u.id, FORMAT_TIMESTAMP('%Y%m%d', TIMESTAMP(CAST(u.dateload AS DATE))), ROW_NUMBER() OVER(ORDER BY CAST(u.dateload AS DATE), u.id)) AS BIGNUMERIC) AS sk_user 
            FROM {dataset_trusted}.user as u
            INNER JOIN {dataset_trusted}.idiom as id ON u.database = id.database AND u.idiom_id = id.id
            LEFT JOIN {dataset_trusted}.hierarchy hy ON u.database = hy.database   AND u.id = hy.subordinateid 
            LEFT JOIN {dataset_trusted}.team as tm ON u.team_id = tm.id AND u.database = tm.database
			--LEFT JOIN {dataset_trusted}.userexcludente ur ON u.database = ur.database AND u.id = ur.user_restrict OR hy.database = ur.database AND hy.leaderid = ur.user_restrict
                WHERE u.cdc_commit_timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {interval_time} HOUR)
) AS S

ON (T.database = S.database AND T.user_id = S.user_id AND T.team_id > 0)
WHEN MATCHED  AND T.dateload < S.dateload THEN
  UPDATE SET 
                    user_id = S.user_id,
                    team_id = S.team_id,
                    usertype_id = S.usertype_id,
                    userstatus_id = S.userstatus_id,
                    useravatar_id = S.useravatar_id,
                    template_id = S.template_id,
                    agentid = S.agentid,
                    externalid = S.externalid,
                    username = S.username,
                    name = S.name,
                    lastname = S.lastname,
                    email = S.email,
                    place = S.place,
                    cell = S.cell,
                    position = S.position,
                    phone = S.phone,
                    branch = S.branch,
                    cellphone = S.cellphone,
                    description = S.description,
                    password = S.password,
                    img = S.img,
                    newsletter = S.newsletter,
                    level = S.level,
                    touruser = S.touruser,
                    touradm = S.touradm,
                    entrytime = S.entrytime,
                    exittime = S.exittime,
                    acceptprivacy = S.acceptprivacy,
                    blockdm = S.blockdm,
                    blockmobile = S.blockmobile,
                    blockscale = S.blockscale,
                    changepassword = S.changepassword,
                    status = S.status,
                    uac_id = S.uac_id,
                    cpf = S.cpf,
                    leader = S.leader,
                    changeusername = S.changeusername,
                    mention = S.mention,
                    nid = S.nid,
                    created = S.created,
                    created_by = S.created_by,
                    idiom_id = S.idiom_id,
                    idiom_code = S.idiom_code,
                    fuso_name = S.fuso_name,
                    login = S.login,
                    acceptprivacy_datetime = S.acceptprivacy_datetime,
                    acceptprivacy_from = S.acceptprivacy_from,
                    acceptprivacystore = S.acceptprivacystore,
                    hierarchy_leaderid = S.hierarchy_leaderid,
                    subdomain = S.subdomain,
                    mood_lastchange = S.mood_lastchange,
					restricted_user = S.restricted_user,
                    database = S.database,
					scd_finished = CURRENT_TIMESTAMP(),
					scd_activate = 0
WHEN NOT MATCHED THEN
  INSERT (
                    user_id,
                    team_id,
                    usertype_id,
                    userstatus_id,
                    useravatar_id,
                    template_id,
                    agentid,
                    externalid,
                    username,
                    name,
                    lastname,
                    email,
                    place,
                    cell,
                    position,
                    phone,
                    branch,
                    cellphone,
                    description,
                    password,
                    img,
                    newsletter,
                    level,
                    touruser,
                    touradm,
                    entrytime,
                    exittime,
                    acceptprivacy,
                    blockdm,
                    blockmobile,
                    blockscale,
                    changepassword,
                    status,
                    uac_id,
                    cpf,
                    leader,
                    changeusername,
                    mention,
                    nid,
                    created,
                    created_by,
                    idiom_id,
                    idiom_code,
                    fuso_name,
                    login,
                    acceptprivacy_datetime,
                    acceptprivacy_from,
                    acceptprivacystore,
                    hierarchy_leaderid,
                    subdomain,
                    mood_lastchange,
					restricted_user,
                    database,
                    dateload,
					sk_user,
					scd_started,
					scd_finished,
					scd_activate
                    )
  VALUES (  
                    S.user_id,
                    S.team_id,
                    S.usertype_id,
                    S.userstatus_id,
                    S.useravatar_id,
                    S.template_id,
                    S.agentid,
                    S.externalid,
                    S.username,
                    S.name,
                    S.lastname,
                    S.email,
                    S.place,
                    S.cell,
                    S.position,
                    S.phone,
                    S.branch,
                    S.cellphone,
                    S.description,
                    S.password,
                    S.img,
                    S.newsletter,
                    S.level,
                    S.touruser,
                    S.touradm,
                    S.entrytime,
                    S.exittime,
                    S.acceptprivacy,
                    S.blockdm,
                    S.blockmobile,
                    S.blockscale,
                    S.changepassword,
                    S.status,
                    S.uac_id,
                    S.cpf,
                    S.leader,
                    S.changeusername,
                    S.mention,
                    S.nid,
                    S.created,
                    S.created_by,
                    S.idiom_id,
                    S.idiom_code,
                    S.fuso_name,
                    S.login,
                    S.acceptprivacy_datetime,
                    S.acceptprivacy_from,
                    S.acceptprivacystore,
                    S.hierarchy_leaderid,
                    S.subdomain,
                    S.mood_lastchange,
					S.restricted_user,
                    S.database,
                    S.dateload,
					S.sk_user,
					CURRENT_TIMESTAMP(),
					'1900-01-01 00:00:00',
					1
                    )